### ISSUE TITLE
Update balancer SOR API to v3

### ISSUE THREAD

**Issue by MartinquaXD** [gnosis/solvers#17]
The balancer team is updating their SOR API and plans on deprecating older APIs.
The v3 can be found [here](https://api-v3.balancer.fi/).
`sorGetSwaps` currently queries the old and the new router and returns the better response but this endpoint will be deprecated soon-ish. That's why `sorGetSwapPaths` should be used although the new router returns worse results in 10% of the time at the moment (should be fixed eventually).

The parameters of the new API are pretty self explanatory with 1 exception:
If `queryBatchSwap` is set to false the `returnAmount` will be computed off of cached values. Note that this setting should not change at all which trade route gets picked (they say they are able to find the optimal route with cached values) it's just that the `returnAmount` might not be 100% accurate.

Since all quotes will eventually be verified using simulations this flag could be set to `false` for quoting but to not handle quoting and actual solving differently it's probably easiest to just set it to `true` unless we can see very significant latency reductions when quoting without it.

Over all upgrading the API itself should be fairly easy. The bigger issues is that a bunch of tests rely on the old API format and updating those will be a bit of work.

**Comment by squadgazzz** [comment]
May I ask you to clarify what exactly is required to be done by this task?
We are using [/sor/{chain_id}](https://docs.balancer.fi/guides/API/usage.html#using-the-api) API endpoint where in the body a [SOR query](https://github.com/balancer/balancer-api#smart-order-router-queries) is sent which returns [SerializedSwapInfo](https://github.com/balancer/balancer-api/blob/master/src/modules/sor/types.ts). Do we need to change the request body/endpoint/response?
